#! /bin/sh



bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 27

bspc config split_ratio          0.52
bspc config borderless_monocle  false 
bspc config gapless_monocle     false 

bspc rule -a Zathura state=tiled
#polybar -c ~/.config/polybar/lite lite &
lemonbar_pywal_icons &
picom --experimental-backends &
feh --bg-scale ~/.config/wal/bumblebee.jpg

#configure bspwm to follow pywal colourscheme
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color15"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

#autorun
setxkbmap dvorak -option caps:escape; sxhkd &
wal -R 
dunst -conf ~/.dunst/dunstrc &
